### PR TITLE
Add KeyProtect functionality 

### PR DESCRIPTION
**Pull request by lumjjb**
To address https://github.com/IBM/k8s-enc-image-operator/issues/4

1. Refactor for generic secret handlers
2. Implement keyprotect secret handler
3. Implement main binary use of keyprotect and configuration
4. Containerize keyprotect configuration with sample deployment in `deploy/`
5. Sample workflow documentation in `KEYPROTECT.md`

This PR does NOT include (will be covered by future PRs):
1. Unit tests for secret handlers 
2. Helm installation changes for keyprotect
3. OperatorHub.io operator changes for keyprotect

### CODE REVIEW

**Comment by lumjjb** [comment]
@attiss

**Review by sjhx — CHANGES_REQUESTED** [review]
Would it be possible to have some unit tests round the new function?

**Comment by lumjjb** [comment]
Yea - let me write some unit tests for secret handlers. I'll implement it today

**Review by sjhx — APPROVED** [review]
lgtm

**Pull request merged**
